version: '3'

# Define the services/containers to be run
services:
  app: #name of your service
    build: ./ # specify the directory of the Dockerfile
    command: npm start
    container_name: api-app
    restart: on-failure
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "80:8080" #specify ports forwarding
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - database

  database: # name of the service
    image: mongo # specify image to build container from
    container_name: api-db
    ports:
     - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
